(function(e){"function"===typeof define&&define.amd?define(["jquery"],e):"object"===typeof module&&module.exports?module.exports=e(require("jquery")):e(jQuery)})(function(e){var r=Array.prototype.slice,w=Array.prototype.splice,p={topSpacing:0,bottomSpacing:0,className:"is-sticky",wrapperClassName:"sticky-wrapper",center:!1,getWidthFrom:"",widthFromWrapper:!0,responsiveWidth:!1,zIndex:"inherit"},q=e(window),x=e(document),k=[],t=q.height(),n=function(){var b=q.scrollTop(),d=x.height(),c=d-t;c=b>c?c-
b:0;for(var f=0,l=k.length;f<l;f++){var a=k[f],g=a.stickyWrapper.offset().top-a.topSpacing-c;a.stickyWrapper.css("height",a.stickyElement.outerHeight());if(b<=g)null!==a.currentTop&&(a.stickyElement.css({width:"",position:"",top:"","z-index":""}),a.stickyElement.parent().removeClass(a.className),a.stickyElement.trigger("sticky-end",[a]),a.currentTop=null);else{g=d-a.stickyElement.outerHeight()-a.topSpacing-a.bottomSpacing-b-c;g=0>g?g+a.topSpacing:a.topSpacing;if(a.currentTop!==g){if(a.getWidthFrom){padding=
a.stickyElement.innerWidth()-a.stickyElement.width();var m=e(a.getWidthFrom).width()-padding||null}else a.widthFromWrapper&&(m=a.stickyWrapper.width());null==m&&(m=a.stickyElement.width());a.stickyElement.css("width",m).css("position","fixed").css("top",g).css("z-index",a.zIndex);a.stickyElement.parent().addClass(a.className);null===a.currentTop?a.stickyElement.trigger("sticky-start",[a]):a.stickyElement.trigger("sticky-update",[a]);a.currentTop===a.topSpacing&&a.currentTop>g||null===a.currentTop&&
g<a.topSpacing?a.stickyElement.trigger("sticky-bottom-reached",[a]):null!==a.currentTop&&g===a.topSpacing&&a.currentTop<g&&a.stickyElement.trigger("sticky-bottom-unreached",[a]);a.currentTop=g}var u=a.stickyWrapper.parent();a.stickyElement.offset().top+a.stickyElement.outerHeight()>=u.offset().top+u.outerHeight()&&a.stickyElement.offset().top<=a.topSpacing?a.stickyElement.css("position","absolute").css("top","").css("bottom",0).css("z-index",""):a.stickyElement.css("position","fixed").css("top",g).css("bottom",
"").css("z-index",a.zIndex)}}},v=function(){t=q.height();for(var b=0,d=k.length;b<d;b++){var c=k[b],f=null;c.getWidthFrom?c.responsiveWidth&&(f=e(c.getWidthFrom).width()):c.widthFromWrapper&&(f=c.stickyWrapper.width());null!=f&&c.stickyElement.css("width",f)}},h={init:function(b){return this.each(function(){var d=e.extend({},p,b),c=e(this),f=c.attr("id"),l=f?f+"-"+p.wrapperClassName:p.wrapperClassName,a=e("<div></div>").attr("id",l).addClass(d.wrapperClassName);c.wrapAll(function(){if(0==e(this).parent("#"+
l).length)return a});f=c.parent();d.center&&f.css({width:c.outerWidth(),marginLeft:"auto",marginRight:"auto"});"right"===c.css("float")&&c.css({"float":"none"}).parent().css({"float":"right"});d.stickyElement=c;d.stickyWrapper=f;d.currentTop=null;k.push(d);h.setWrapperHeight(this);h.setupChangeListeners(this)})},setWrapperHeight:function(b){b=e(b);var d=b.parent();d&&d.css("height",b.outerHeight())},setupChangeListeners:function(b){window.MutationObserver?(new window.MutationObserver(function(d){(d[0].addedNodes.length||
d[0].removedNodes.length)&&h.setWrapperHeight(b)})).observe(b,{subtree:!0,childList:!0}):window.addEventListener?(b.addEventListener("DOMNodeInserted",function(){h.setWrapperHeight(b)},!1),b.addEventListener("DOMNodeRemoved",function(){h.setWrapperHeight(b)},!1)):window.attachEvent&&(b.attachEvent("onDOMNodeInserted",function(){h.setWrapperHeight(b)}),b.attachEvent("onDOMNodeRemoved",function(){h.setWrapperHeight(b)}))},update:n,unstick:function(b){return this.each(function(){for(var d=e(this),c=
-1,f=k.length;0<f--;)k[f].stickyElement.get(0)===this&&(w.call(k,f,1),c=f);-1!==c&&(d.unwrap(),d.css({width:"",position:"",top:"","float":"","z-index":""}))})}};window.addEventListener?(window.addEventListener("scroll",n,!1),window.addEventListener("resize",v,!1)):window.attachEvent&&(window.attachEvent("onscroll",n),window.attachEvent("onresize",v));e.fn.sticky=function(b){if(h[b])return h[b].apply(this,r.call(arguments,1));if("object"!==typeof b&&b)e.error("Method "+b+" does not exist on jQuery.sticky");
else return h.init.apply(this,arguments)};e.fn.unstick=function(b){if(h[b])return h[b].apply(this,r.call(arguments,1));if("object"!==typeof b&&b)e.error("Method "+b+" does not exist on jQuery.sticky");else return h.unstick.apply(this,arguments)};e(function(){setTimeout(n,0)})});
