/*
 jQuery Migrate - v1.0.0 - 2013-01-14
 https://github.com/jquery/jquery-migrate
 Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors; Licensed MIT
*/
(function(b,C,p){function g(a){r[a]||(r[a]=!0,b.migrateWarnings.push(a),C.console&&console.warn&&!b.migrateMute&&console.warn("JQMIGRATE: "+a))}function q(a,c,d,f){if(Object.defineProperty)try{Object.defineProperty(a,c,{configurable:!0,enumerable:!0,get:function(){g(f);return d},set:function(e){g(f);d=e}});return}catch(e){}b._definePropertyBroken=!0;a[c]=d}var r={};b.migrateWarnings=[];b.migrateReset=function(){r={};b.migrateWarnings.length=0};"BackCompat"===document.compatMode&&g("jQuery is not compatible with Quirks Mode");
var D=b.attr,E=b.attrHooks.value&&b.attrHooks.value.get||function(){return null},F=b.attrHooks.value&&b.attrHooks.value.set||function(){return p},G=/^(?:input|button)$/i,H=/^[238]$/,I=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,J=/^(?:checked|selected)$/i;q(b,"attrFn",{},"jQuery.attrFn is deprecated");b.attr=function(a,c,d,f){var e=c.toLowerCase(),k=a&&a.nodeType;if(f&&(g("jQuery.fn.attr( props, pass ) is deprecated"),
a&&!H.test(k)&&b.isFunction(b.fn[c])))return b(a)[c](d);"type"===c&&d!==p&&G.test(a.nodeName)&&g("Can't change the 'type' of an input or button in IE 6/7/8");!b.attrHooks[e]&&I.test(e)&&(b.attrHooks[e]={get:function(h,l){var m,u=b.prop(h,l);return!0===u||"boolean"!==typeof u&&(m=h.getAttributeNode(l))&&!1!==m.nodeValue?l.toLowerCase():p},set:function(h,l,m){!1===l?b.removeAttr(h,m):(l=b.propFix[m]||m,l in h&&(h[l]=!0),h.setAttribute(m,m.toLowerCase()));return m}},J.test(e)&&g("jQuery.fn.attr("+e+
") may use property instead of attribute"));return D.call(b,a,c,d)};b.attrHooks.value={get:function(a,c){var d=(a.nodeName||"").toLowerCase();if("button"===d)return E.apply(this,arguments);"input"!==d&&"option"!==d&&g("property-based jQuery.fn.attr('value') is deprecated");return c in a?a.value:null},set:function(a,c){var d=(a.nodeName||"").toLowerCase();if("button"===d)return F.apply(this,arguments);"input"!==d&&"option"!==d&&g("property-based jQuery.fn.attr('value', val) is deprecated");a.value=
c}};var v=b.fn.init,K=/^(?:.*(<[\w\W]+>)[^>]*|#([\w\-]*))$/;b.fn.init=function(a,c,d){var f;return a&&"string"===typeof a&&!b.isPlainObject(c)&&(f=K.exec(a))&&f[1]&&("<"!==a.charAt(0)&&g("$(html) HTML strings must start with '<' character"),c&&c.context&&(c=c.context),b.parseHTML)?v.call(this,b.parseHTML(b.trim(a),c,!0),c,d):v.apply(this,arguments)};b.fn.init.prototype=b.fn;b.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||
/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};var t=b.uaMatch(navigator.userAgent);var n={};t.browser&&(n[t.browser]=!0,n.version=t.version);n.chrome?n.webkit=!0:n.webkit&&(n.safari=!0);b.browser=n;q(b,"browser",n,"jQuery.browser is deprecated");b.sub=function(){function a(d,f){return new a.fn.init(d,f)}b.extend(!0,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=
function(d,f){f&&f instanceof b&&!(f instanceof a)&&(f=a(f));return b.fn.init.call(this,d,f,c)};a.fn.init.prototype=a.fn;var c=a(document);g("jQuery.sub() is deprecated");return a};var L=b.fn.data;b.fn.data=function(a){var c;if((c=this[0])&&"events"===a&&1===arguments.length){var d=b.data(c,a);c=b._data(c,a);if((d===p||d===c)&&c!==p)return g("Use of jQuery.fn.data('events') is deprecated"),c}return L.apply(this,arguments)};var M=/\/(java|ecma)script/i,N=b.fn.andSelf||b.fn.addBack,w=b.buildFragment;
b.fn.andSelf=function(){g("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()");return N.apply(this,arguments)};b.clean||(b.clean=function(a,c,d,f){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;g("jQuery.clean() is deprecated");var e,k=[];b.merge(k,b.buildFragment(a,c).childNodes);if(d)for(c=function(h){if(!h.type||M.test(h.type))return f?f.push(h.parentNode?h.parentNode.removeChild(h):h):d.appendChild(h)},a=0;null!=(e=k[a]);a++)b.nodeName(e,"script")&&c(e)||(d.appendChild(e),"undefined"!==
typeof e.getElementsByTagName&&(e=b.grep(b.merge([],e.getElementsByTagName("script")),c),k.splice.apply(k,[a+1,0].concat(e)),a+=e.length));return k});b.buildFragment=function(a,c,d,f){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;try{var e=w.call(b,a,c,d,f)}catch(k){e=w.call(b,a,c.nodeType?[c]:c[0],d,f),g("jQuery.buildFragment() is deprecated")}e.fragment||(q(e,"fragment",e,"jQuery.buildFragment() is deprecated"),q(e,"cacheable",!1,"jQuery.buildFragment() is deprecated"));return e};var O=
b.event.add,P=b.event.remove,Q=b.event.trigger,R=b.fn.toggle,x=b.fn.live,y=b.fn.die,z=RegExp("\\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\\b"),A=/(?:^|\s)hover(\.\S+|)\b/,B=function(a){if("string"!=typeof a||b.event.special.hover)return a;A.test(a)&&g("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'");return a&&a.replace(A,"mouseenter$1 mouseleave$1")};b.event.props&&"attrChange"!==b.event.props[0]&&b.event.props.unshift("attrChange","attrName","relatedNode",
"srcElement");q(b.event,"handle",b.event.dispatch,"jQuery.event.handle is undocumented and deprecated");b.event.add=function(a,c,d,f,e){a!==document&&z.test(c)&&g("AJAX events should be attached to document: "+c);O.call(this,a,B(c||""),d,f,e)};b.event.remove=function(a,c,d,f,e){P.call(this,a,B(c)||"",d,f,e)};b.fn.error=function(){var a=Array.prototype.slice.call(arguments,0);g("jQuery.fn.error() is deprecated");a.splice(0,0,"error");if(arguments.length)return this.bind.apply(this,a);this.triggerHandler.apply(this,
a);return this};b.fn.toggle=function(a,c){if(!b.isFunction(a)||!b.isFunction(c))return R.apply(this,arguments);g("jQuery.fn.toggle(handler, handler...) is deprecated");var d=arguments,f=a.guid||b.guid++,e=0,k=function(h){var l=(b._data(this,"lastToggle"+a.guid)||0)%e;b._data(this,"lastToggle"+a.guid,l+1);h.preventDefault();return d[l].apply(this,arguments)||!1};for(k.guid=f;e<d.length;)d[e++].guid=f;return this.click(k)};b.fn.live=function(a,c,d){g("jQuery.fn.live() is deprecated");if(x)return x.apply(this,
arguments);b(this.context).on(a,this.selector,c,d);return this};b.fn.die=function(a,c){g("jQuery.fn.die() is deprecated");if(y)return y.apply(this,arguments);b(this.context).off(a,this.selector||"**",c);return this};b.event.trigger=function(a,c,d,f){!d&!z.test(a)&&g("Global events are undocumented and deprecated");return Q.call(this,a,c,d||document,f)};b.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(a,c){b.event.special[c]={setup:function(){var d=this;d!==
document&&(b.event.add(document,c+"."+b.guid,function(){b.event.trigger(c,null,d,!0)}),b._data(this,c,b.guid++));return!1},teardown:function(){this!==document&&b.event.remove(document,c+"."+b._data(this,c));return!1}}})})(jQuery,window);
