function getScrollBarWidth(){var a=document.createElement("p");a.style.width="100%";a.style.height="200px";var b=document.createElement("div");b.style.position="absolute";b.style.top="0px";b.style.left="0px";b.style.visibility="hidden";b.style.width="200px";b.style.height="150px";b.style.overflow="hidden";b.appendChild(a);document.body.appendChild(b);var c=a.offsetWidth;b.style.overflow="scroll";a=a.offsetWidth;c==a&&(a=b.clientWidth);document.body.removeChild(b);return c-a}
function setMenuHeight(){$("#sidebar .highlightable").height($("#sidebar").innerHeight()-$("#header-wrapper").height()-40);$("#sidebar .highlightable").perfectScrollbar("update")}function fallbackMessage(a){var b="cut"===a?"X":"C";return/iPhone|iPad/i.test(navigator.userAgent)?"No support :(":/Mac/i.test(navigator.userAgent)?"Press \u2318-"+b+" to "+a:"Press Ctrl-"+b+" to "+a}
function switchTab(a,b){allTabItems=jQuery("[data-tab-group='"+a+"']");targetTabItems=jQuery("[data-tab-group='"+a+"'][data-tab-item='"+b+"']");var c=void 0!=event;if(c)var d=event.target.getBoundingClientRect().top;allTabItems.removeClass("active");targetTabItems.addClass("active");c&&(c=event.target.getBoundingClientRect().top-d,window.scrollTo(window.scrollX,window.scrollY+c),window.localStorage&&(c=(c=window.localStorage.getItem("tabSelections"))?JSON.parse(c):{},c[a]=b,window.localStorage.setItem("tabSelections",
JSON.stringify(c))))}function restoreTabSelections(){if(window.localStorage){var a=window.localStorage.getItem("tabSelections"),b=a?JSON.parse(a):{};Object.keys(b).forEach(function(c){switchTab(c,b[c])})}}$(window).resize(function(){setMenuHeight()});
(function(a,b){var c=function(d,e,h){var g;return function(){var f=this,k=arguments;g?clearTimeout(g):h&&d.apply(f,k);g=setTimeout(function(){h||d.apply(f,k);g=null},e||100)}};jQuery.fn[b]=function(d){return d?this.bind("resize",c(d)):this.trigger(b)}})(jQuery,"smartresize");
jQuery(document).ready(function(){restoreTabSelections();jQuery("#sidebar .category-icon").on("click",function(){$(this).toggleClass("fa-angle-down fa-angle-right");$(this).parent().parent().children("ul").toggle();return!1});var a=searchStatus="open";$("#sidebar .highlightable").perfectScrollbar();setMenuHeight();jQuery("#overlay").on("click",function(){jQuery(document.body).toggleClass("sidebar-hidden");a=jQuery(document.body).hasClass("sidebar-hidden")?"closed":"open";return!1});jQuery("[data-sidebar-toggle]").on("click",
function(){jQuery(document.body).toggleClass("sidebar-hidden");a=jQuery(document.body).hasClass("sidebar-hidden")?"closed":"open";return!1});jQuery("[data-clear-history-toggle]").on("click",function(){sessionStorage.clear();location.reload();return!1});jQuery("[data-search-toggle]").on("click",function(){if("closed"==a)return jQuery("[data-sidebar-toggle]").trigger("click"),jQuery(document.body).removeClass("searchbox-hidden"),searchStatus="open",!1;jQuery(document.body).toggleClass("searchbox-hidden");
searchStatus=jQuery(document.body).hasClass("searchbox-hidden")?"closed":"open";return!1});jQuery("[data-search-input]").on("input",function(){var d=jQuery(this).val(),e=jQuery("[data-nav-id]");e.removeClass("search-match");d.length?(sessionStorage.setItem("search-value",d),$(".highlightable").unhighlight({element:"mark"}).highlight(d,{element:"mark"}),jQuery("[data-search-clear]").on("click",function(){jQuery("[data-search-input]").val("").trigger("input");sessionStorage.removeItem("search-input");
$(".highlightable").unhighlight({element:"mark"})})):($("ul.topics").removeClass("searched"),e.css("display","block"),sessionStorage.removeItem("search-value"),$(".highlightable").unhighlight({element:"mark"}))});$.expr[":"].contains=$.expr.createPseudo(function(d){return function(e){return 0<=$(e).text().toUpperCase().indexOf(d.toUpperCase())}});if(sessionStorage.getItem("search-value")){var b=sessionStorage.getItem("search-value");$(document.body).removeClass("searchbox-hidden");$("[data-search-input]").val(b);
$("[data-search-input]").trigger("input");if(b=$("#body-inner").find(":contains("+b+")").get(0))b.scrollIntoView(!0),(b=window.scrollY)&&window.scroll(0,b-125)}var c=!1;$("code").each(function(){var d=$(this),e=d.text();if(5<e.length){if(!c){var h=new ClipboardJS(".copy-to-clipboard",{text:function(f){e=$(f).prev("code").text();return e.replace(/^\$\s/gm,"")}}),g;h.on("success",function(f){f.clearSelection();g="PRE"==$(f.trigger).parent().prop("tagName");$(f.trigger).attr("aria-label","Copied to clipboard!").addClass("tooltipped tooltipped-"+
(g?"w":"s"))});h.on("error",function(f){g="PRE"==$(f.trigger).parent().prop("tagName");$(f.trigger).attr("aria-label",fallbackMessage(f.action)).addClass("tooltipped tooltipped-"+(g?"w":"s"));$(document).one("copy",function(){$(f.trigger).attr("aria-label","Copied to clipboard!").addClass("tooltipped tooltipped-"+(g?"w":"s"))})});c=!0}d.after('<span class="copy-to-clipboard" title="Copy to clipboard" />');d.next(".copy-to-clipboard").on("mouseleave",function(){$(this).attr("aria-label",null).removeClass("tooltipped tooltipped-s tooltipped-w")})}});
jQuery(function(){jQuery(".nav-prev").click(function(){location.href=jQuery(this).attr("href")});jQuery(".nav-next").click(function(){location.href=jQuery(this).attr("href")})});jQuery("input, textarea").keydown(function(d){"37"!=d.which&&"39"!=d.which||d.stopPropagation()});jQuery(document).keydown(function(d){"37"==d.which&&jQuery(".nav.nav-prev").click();"39"==d.which&&jQuery(".nav.nav-next").click()});$("#top-bar a:not(:has(img)):not(.btn)").addClass("highlight");$('#body-inner a:not(:has(img)):not(.btn):not(a[rel="footnote"])').addClass("highlight");
b="ontouchstart"in window||0<navigator.maxTouchPoints||0<navigator.msMaxTouchPoints;b||($("#toc-menu").hover(function(){$(".progress").stop(!0,!1,!0).fadeToggle(100)}),$(".progress").hover(function(){$(".progress").stop(!0,!1,!0).fadeToggle(100)}));b&&($("#toc-menu").click(function(){$(".progress").stop(!0,!1,!0).fadeToggle(100)}),$(".progress").click(function(){$(".progress").stop(!0,!1,!0).fadeToggle(100)}));(function(d,e,h){var g=!(!e||!e.pushState);$(d).ready($.proxy({ANCHOR_REGEX:/^#[^ ]+$/,
OFFSET_HEIGHT_PX:50,init:function(){this.scrollToCurrent();$(window).on("hashchange",$.proxy(this,"scrollToCurrent"));$("body").on("click","a",$.proxy(this,"delegateAnchors"))},getFixedOffset:function(){return this.OFFSET_HEIGHT_PX},scrollIfAnchor:function(f,k){var l;if(!this.ANCHOR_REGEX.test(f))return!1;if(l=d.getElementById(f.slice(1))){var m=$(l).offset().top-this.getFixedOffset();$("html, body").animate({scrollTop:m});g&&k&&e.pushState({},d.title,h.pathname+f)}return!!l},scrollToCurrent:function(f){this.scrollIfAnchor(window.location.hash)&&
f&&f.preventDefault()},delegateAnchors:function(f){this.scrollIfAnchor(f.target.getAttribute("href"),!0)&&f.preventDefault()}},"init"))})(window.document,window.history,window.location)});jQuery(window).on("load",function(){sessionStorage.setItem(jQuery("body").data("url"),1);for(var a in sessionStorage)1==sessionStorage.getItem(a)&&jQuery('[data-nav-id="'+a+'"]').addClass("visited");$(".highlightable").highlight(sessionStorage.getItem("search-value"),{element:"mark"})});$(function(){$('a[rel="lightbox"]').featherlight({root:"section#body"})});
jQuery.extend({highlight:function(a,b,c,d){if(3===a.nodeType){if(b=a.data.match(b))return c=document.createElement(c||"span"),c.className=d||"highlight",a=a.splitText(b.index),a.splitText(b[0].length),d=a.cloneNode(!0),c.appendChild(d),a.parentNode.replaceChild(c,a),1}else if(1===a.nodeType&&a.childNodes&&!/(script|style)/i.test(a.tagName)&&(a.tagName!==c.toUpperCase()||a.className!==d))for(var e=0;e<a.childNodes.length;e++)e+=jQuery.highlight(a.childNodes[e],b,c,d);return 0}});
jQuery.fn.unhighlight=function(a){var b={className:"highlight",element:"span"};jQuery.extend(b,a);return this.find(b.element+"."+b.className).each(function(){var c=this.parentNode;c.replaceChild(this.firstChild,this);c.normalize()}).end()};
jQuery.fn.highlight=function(a,b){var c={className:"highlight",element:"span",caseSensitive:!1,wordsOnly:!1};jQuery.extend(c,b);if(a){a.constructor===String&&(a=[a]);a=jQuery.grep(a,function(e,h){return""!=e});a=jQuery.map(a,function(e,h){return e.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")});if(0==a.length)return this;b=c.caseSensitive?"":"i";a="("+a.join("|")+")";c.wordsOnly&&(a="\\b"+a+"\\b");var d=new RegExp(a,b);return this.each(function(){jQuery.highlight(this,d,c.element,c.className)})}};
