function importCss(){document.write('<link rel="stylesheet" href="/karel/css/style.css" type="text/css" /><link rel="stylesheet" href="/karel/boxy/stylesheets/boxy.css" type="text/css" />')}function createImageButton(a,b,e,d,c){d=document.createElement("button");var f=document.createElement("img");f.setAttribute("src",b);f.setAttribute("height",30);f.setAttribute("width",30);d.appendChild(f);d.id=e;d.className="interactor";c&&(d.className=c);a.appendChild(d);return d}
function createTextButton(a,b,e,d){var c=document.createElement("button");c.className=d;c.innerHTML=b;c.id=e;a.appendChild(c);return c}function addText(a,b){a.innerHTML+=b}function addSpace(a){addText(a,"&nbsp;")}function addWorldDropDown(a,b){b=document.createElement("button");b.className="btn btn-default dropdown-toggle pull-left interactor";b.setAttribute("type","button");b.setAttribute("data-toogle","dropdown");b.innerHTML='World <span class="caret"></span>';a.appendChild(b);return b}
function importPythonEditor(a,b,e,d){var c=document.createElement("div");c.innerHTML=e;c.id=a;c.className="ideEditor";b=document.getElementById(b);console.log(b);b.appendChild(c);a=ace.edit(a);a.setTheme("ace/theme/eclipse");b=require("ace/mode/python").Mode;a.getSession().setMode(new b);a.getSession().setUseWrapMode(!0);a.setReadOnly(!d);a.getSession().setOptions({tabSize:3,useSoftTabs:!0});a.renderer.setShowGutter(!1);a.getSession().setUseWorker(!1);c.style.fontSize="13px";return a}
function importEditorCode(a,b,e,d){var c=document.createElement("div");c.innerHTML=e;c.id=a;c.className="ideEditor";b=document.getElementById(b);console.log(b);b.appendChild(c);a=ace.edit(a);a.setTheme("ace/theme/eclipse");b=require("ace/mode/java").Mode;a.getSession().setMode(new b);a.getSession().setUseWrapMode(!0);a.setReadOnly(!d);a.getSession().setOptions({tabSize:3,useSoftTabs:!0});a.renderer.setShowGutter(!1);a.getSession().setUseWorker(!1);c.style.fontSize="13px";return a}
function importEditor(a,b){return importEditorCode(a,b,STARTER_CODE)}function importRunButtonBar(a){a=document.getElementById(a);createTextButton(a,'<span class="glyphicon glyphicon-play"></span> Run Program',"playButton","btn btn-primary interactor")}function importScripts(a){for(var b="",e=0;e<a.length;e++)b+=a[e];document.write(b)}
function importJsLibraries(){importScripts('<script src="/karel/lib/browser_detect.js">\x3c/script>;<script src="/karel/lib/util.js">\x3c/script>;<script src="/karel/lib/tabs.js">\x3c/script>;<script src="/karel/codeMirror/js/codemirror.js">\x3c/script>;<script src="/karel/ace/ace.js">\x3c/script>;<script src="/karel/ace/theme-eclipse.js">\x3c/script>;<script src="/karel/ace/mode-javascript.js">\x3c/script>;<script src="/karel/ace/mode-java.js">\x3c/script>;<script src="/karel/ace/mode-python.js">\x3c/script>;<script src="/karel/lib/curvycorners.js">\x3c/script>;<script src="/karel/lib/jquery.js">\x3c/script>;<script src="/karel/boxy/jquery.boxy.js">\x3c/script>;<script src="/karel/lib/swal.min.js">\x3c/script>'.split(";"))}
function importKarelIde(){importScripts('<script src="/karel/js/ide/karelImages.js">\x3c/script>;<script src="/karel/js/ide/karelSingleton.js">\x3c/script>;<script src="/karel/js/ide/karelConstants.js">\x3c/script>;<script src="/karel/js/ide/action.js">\x3c/script>;<script src="/karel/js/ide/beepers.js">\x3c/script>;<script src="/karel/js/ide/walls.js">\x3c/script>;<script src="/karel/js/ide/squareColors.js">\x3c/script>;<script src="/karel/js/ide/canvasModel.js">\x3c/script>;<script src="/karel/js/ide/karelModel.js">\x3c/script>;<script src="/karel/js/ide/karelView.js">\x3c/script>;<script src="/karel/js/ide/karel.js">\x3c/script>;<script src="/karel/js/ide/karelCompiledEngine.js">\x3c/script>;<script src="/karel/js/ide/karelEvalEngine.js">\x3c/script>;<script src="/karel/js/ide/karelIde.js">\x3c/script>;<script src="/karel/js/html/starterCode.js">\x3c/script>'.split(";"))}
function importCompiler(){importScripts('<script src="/karel/js/compiler/karelJavaCompiler.js">\x3c/script>;<script src="/karel/js/compiler/karelPythonCompiler.js">\x3c/script>;<script src="/karel/js/compiler/scanner/TokenScanner.js">\x3c/script>;<script src="/karel/js/compiler/parser/Parser.js">\x3c/script>;<script src="/karel/js/compiler/parser/XParser.js">\x3c/script>;<script src="/karel/js/compiler/vm/VM.js">\x3c/script>;<script src="/karel/js/compiler/vm/XVM.js">\x3c/script>;<script src="/karel/js/compiler/karel/KarelParser.js">\x3c/script>;<script src="/karel/js/compiler/karel/KarelPythonParser.js">\x3c/script>;<script src="/karel/js/compiler/karel/KarelVM.js">\x3c/script>'.split(";"))}
function importLearnEngine(){importScripts([])}function importReference(){importScripts(['<script src="/karel/js/dialog/referenceDialog.js">\x3c/script>','<script src="/karel/js/dialog/deployDialog.js">\x3c/script>'])}function importJs(){importJsLibraries();importCompiler();importKarelIde();importLearnEngine();importReference()};
