function KarelModel(){function k(b){switch(b){case 0:return"North";case 1:return"East";case 2:return"South";case 3:return"West"}}function g(b){return b?"clear":"blocked"}function h(b){var c=b.indexOf("("),f=b.indexOf(")");b=b.substring(c+1,f);coordStrings=b.split(",");b=parseInt(coordStrings[0]);c=parseInt(coordStrings[1]);return[b,c]}function l(b){a.nBeepersInBag=eval(b)}function m(b){var c=h(b),f=a.rows-c[0];c=c[1]-1;var d=b.indexOf(")")+1;b=(b=b.substring(d).trim())?eval(b):1;for(d=0;d<b;d++)a.beepers.putBeeper(f,
c)}var a={};a.dir=Const.KAREL_EAST;a.karelRow=0;a.karelCol=0;a.beepers=null;a.walls=null;a.squareColors=null;a.rows=0;a.cols=0;a.nBeepersInBag=Infinity;a.karelHistory=[];a.deepCopy=function(){var b=KarelModel();b.dir=a.dir;b.karelRow=a.karelRow;b.karelCol=a.karelCol;b.beepers=a.beepers.deepCopy();b.walls=a.walls.deepCopy();b.squareColors=a.squareColors.deepCopy();b.rows=a.rows;b.cols=a.cols;return b};a.equals=function(b){return a.dir==b.dir&&a.karelRow==b.karelRow&&a.karelCol==b.karelCol&&a.beepers.equals(b.beepers)&&
a.squareColors.equals(b.squareColors)?!0:!1};a.move=function(){var b=a.karelRow,c=a.karelCol;switch(a.dir){case Const.KAREL_EAST:c+=1;break;case Const.KAREL_WEST:--c;break;case Const.KAREL_NORTH:--b;break;case Const.KAREL_SOUTH:b+=1;break;default:alert("invalid that.dir: "+a.dir)}if(a.walls.isMoveValid(a.karelRow,a.karelCol,b,c))a.karelRow=b,a.karelCol=c;else throw"Front Is Blocked";};a.turnLeft=function(){var b=a.dir;switch(a.dir){case Const.KAREL_EAST:b=Const.KAREL_NORTH;break;case Const.KAREL_WEST:b=
Const.KAREL_SOUTH;break;case Const.KAREL_NORTH:b=Const.KAREL_WEST;break;case Const.KAREL_SOUTH:b=Const.KAREL_EAST;break;default:alert("invalid that.dir: "+a.dir)}a.dir=b};a.turnRight=function(){var b=a.dir;switch(a.dir){case Const.KAREL_EAST:b=Const.KAREL_SOUTH;break;case Const.KAREL_WEST:b=Const.KAREL_NORTH;break;case Const.KAREL_NORTH:b=Const.KAREL_EAST;break;case Const.KAREL_SOUTH:b=Const.KAREL_WEST;break;default:alert("invalid that.dir: "+a.dir)}a.dir=b};a.pickBeeper=function(){if(a.beepers.beeperPresent(a.karelRow,
a.karelCol))a.beepers.pickBeeper(a.karelRow,a.karelCol),a.nBeepersInBag+=1;else throw"No Beepers Present";};a.putBeeper=function(){a.beepers.putBeeper(a.karelRow,a.karelCol);--a.nBeepersInBag};a.turnAround=function(){var b=a.dir;switch(a.dir){case Const.KAREL_EAST:b=Const.KAREL_WEST;break;case Const.KAREL_WEST:b=Const.KAREL_EAST;break;case Const.KAREL_NORTH:b=Const.KAREL_SOUTH;break;case Const.KAREL_SOUTH:b=Const.KAREL_NORTH;break;default:alert("invalid that.dir: "+a.dir)}a.dir=b};a.paintCorner=function(b){a.squareColors.paintCorner(a.karelRow,
a.karelCol,b)};a.getDirection=function(){return a.dir};a.getNBeepersInBag=function(){return a.nBeepersInBag};a.getNumRows=function(){return a.rows};a.getNumCols=function(){return a.cols};a.getKarelRow=function(){return a.karelRow};a.getKarelCol=function(){return a.karelCol};a.getSquareColor=function(b,c){return a.squareColors.getColor(b,c)};a.getNumBeepers=function(b,c){return a.beepers.getNumBeepers(b,c)};a.hasTopWall=function(b,c){return a.walls.topWall(b,c)};a.hasRightWall=function(b,c){return a.walls.rightWall(b,
c)};a.beeperPresent=function(){return a.beepers.beeperPresent(a.karelRow,a.karelCol)};a.frontIsClear=function(){var b=a.karelRow,c=a.karelCol;switch(a.dir){case Const.KAREL_EAST:c+=1;break;case Const.KAREL_WEST:--c;break;case Const.KAREL_NORTH:--b;break;case Const.KAREL_SOUTH:b+=1;break;default:alert("invalid that.dir: "+a.dir)}return a.walls.isMoveValid(a.karelRow,a.karelCol,b,c)};a.rightIsClear=function(){var b=a.karelRow,c=a.karelCol;switch(a.dir){case Const.KAREL_EAST:b+=1;break;case Const.KAREL_WEST:--b;
break;case Const.KAREL_NORTH:c+=1;break;case Const.KAREL_SOUTH:--c;break;default:alert("invalid that.dir: "+a.dir)}return a.walls.isMoveValid(a.karelRow,a.karelCol,b,c)};a.leftIsClear=function(){var b=a.karelRow,c=a.karelCol;switch(a.dir){case Const.KAREL_EAST:--b;break;case Const.KAREL_WEST:b+=1;break;case Const.KAREL_NORTH:--c;break;case Const.KAREL_SOUTH:c+=1;break;default:alert("invalid that.dir: "+a.dir)}return a.walls.isMoveValid(a.karelRow,a.karelCol,b,c)};a.facingNorth=function(){return virtualDirection==
KAREL_NORTH};a.facingSouth=function(){return virtualDirection==KAREL_SOUTH};a.facingEast=function(){return virtualDirection==KAREL_EAST};a.facingWest=function(){return virtualDirection==KAREL_WEST};a.loadWorld=function(b,c){b=b.split("\n");var f=b[0].split(":");assert("Dimension"==f[0],"World file malformed");f=h(f[1]);a.rows=f[0];a.cols=f[1];a.beepers=Beepers(a.rows,a.cols);a.walls=Walls(a.rows,a.cols);a.squareColors=SquareColors(a.rows,a.cols);a.dir=Const.KAREL_EAST;a.karelRow=a.rows-1;a.karelCol=
0;for(f=1;f<b.length;f++)if(""!=b[f]){var d=b[f],e=d.split(":");assert(2==e.length,d+"World file missing :");d=e[0];if("Karel"==d){e=e[1];d=h(e);var n=d[1]-1;a.karelRow=a.rows-d[0];a.karelCol=n;-1!=e.indexOf("west")&&(a.dir=Const.KAREL_WEST);-1!=e.indexOf("south")&&(a.dir=Const.KAREL_SOUTH);-1!=e.indexOf("north")&&(a.dir=Const.KAREL_NORTH)}else"Wall"==d?(d=e[1],e=h(d),-1!=d.indexOf("west")?(d=a.rows-e[1],e=e[0]-2,a.walls.addRightWall(d,e)):(d=a.rows-e[1]+1,e=e[0]-1,a.walls.addTopWall(d,e))):"Beeper"==
d?m(e[1]):"Bag"==d&&l(e[1])}c.setKarelDimensions(a.rows,a.cols)};a.initialWorldText=function(b){var c=`Karel is in a world that has ${a.rows} rows and ${a.cols} columns.`;b&&(c=c.concat(` ${b}`));c=c.concat(` ${a.beepers.beeperText()}.`);return c=c.concat(` Karel is standing on row ${a.rows-a.karelRow} and column ${a.karelCol+1}, facing ${k(a.dir)}. Karel\u2019s front is ${g(a.frontIsClear())}, left is ${g(a.leftIsClear())}, and right is ${g(a.rightIsClear())}.`)};a.moveText=function(b){if(b.includes("turn"))return`Karel ${b} and is now facing ${k(a.dir)}.`;
if(b.includes("move")){var c=a.beepers.getNumBeepers(a.karelRow,a.karelCol);return`Karel ${b} and is now at row ${a.rows-a.karelRow} and column ${a.karelCol+1}, facing ${k(a.dir)}. There ${1==c?"is":"are"} ${c} ${a.beepers.conjugateBeepers(c)} here. Karel\u2019s front is ${g(a.frontIsClear())}, left is ${g(a.leftIsClear())}, and right is ${g(a.rightIsClear())}.`}return b.includes("beeper")?(c=a.beepers.getNumBeepers(a.karelRow,a.karelCol),`Karel ${b}. There ${1==c?"is":"are"} now ${c} ${a.beepers.conjugateBeepers(c)} here.`):
`Karel ${b}.`};return a};
