function KarelCompiler(){}KarelCompiler.addEventListener=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c};function quoteHTML(a){for(var b="",c=0;c<a.length;c++){var d=a.charAt(c);switch(d){case " ":d="&nbsp;";break;case "<":d="&lt;";break;case ">":d="&gt;";break;case "&":d="&amp;"}b+=d}return b}function toStr(a){return"string"==typeof a?a:0>a?"":String.fromCharCode(a)}
function toInt(a){return"string"==typeof a?a&&a.length?a.charCodeAt(0):0:truncate(a)}function truncate(a){return 0>a?Math.ceil(a):Math.floor(a)}function round(a){return Math.round(a)}String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};String.prototype.startsWith=function(a){return this.length<a.length?!1:this.substring(0,a.length)==a};String.prototype.endsWith=function(a){return this.length<a.length?!1:this.substring(this.length-a.length)==a};
String.prototype.compareTo=function(a){return""+this===a?0:this<a?-1:1};String.prototype.equals=function(a){return""+this==a};String.prototype.equalsIgnoreCase=function(a){return this.toLowerCase()===a.toLowerCase()};String.prototype.isEmpty=function(){return 0==this.length};String.compare=function(a,b){return a.compareTo(b)};function Integer(){alert("Error: Can't call Integer constructor")}Integer.parseInt=function(a,b){return parseInt(a,b)};Integer.toString=function(a,b){return a.toString(b)};
function Double(a){alert("Error: Can't call Double constructor")}Double.parseDouble=function(a){return parseFloat(a)};Double.toString=function(a){return a.toString()};function Character(){alert("Error: Can't call Character constructor")}Character.digit=function(a,b){return parseInt(toStr(a),b)};Character.forDigit=function(a,b){return a.toString(b)};Character.isDigit=function(a){return/^\d$/.test(toStr(a))};Character.isJavaIdentifierPart=function(a){return/^[A-Za-z0-9_]$/.test(toStr(a))};
Character.isJavaIdentifierStart=function(a){return/^[A-Za-z_]$/.test(toStr(a))};Character.isLetter=function(a){return/^[A-Za-z]$/.test(toStr(a))};Character.isDigit=function(a){return/^[0-9]$/.test(toStr(a))};Character.isLetterOrDigit=function(a){return/^[A-Za-z0-9]$/.test(toStr(a))};Character.isLowerCase=function(a){return/^[a-z]$/.test(toStr(a))};Character.isUpperCase=function(a){return/^[A-Z]$/.test(toStr(a))};Character.isWhitespace=function(a){return/^\s$/.test(toStr(a))};
Character.toUpperCase=function(a){return a.toUpperCase()};Character.toLowerCase=function(a){return a.toLowerCase()};var isalnum=Character.isLetterOrDigit,isalpha=Character.isLetter,isdigit=Character.isDigit,islower=Character.isLowerCase,isspace=Character.isWhitespace,isupper=Character.isUpperCase,tolower=Character.toLowerCase,toupper=Character.toUpperCase;function iscntrl(a){toInt(a);return 32>a||127==a}function isgraph(a){toInt(a);return 32<a&&127>a}
function isprint(a){toInt(a);return 32<=a&&127>a}function ispunct(a){return isgraph(a)&&!isalnum(a)}function isxdigit(a){return/^[A-Fa-f0-9]$/.test(toStr(a))}
function isMobile(){var a=navigator.userAgent;a=a.toLowerCase();return-1!=a.indexOf("iphone")||-1!=a.indexOf("symbianos")||-1!=a.indexOf("ipad")||-1!=a.indexOf("ipod")||-1!=a.indexOf("android")||-1!=a.indexOf("blackberry")||-1!=a.indexOf("samsung")||-1!=a.indexOf("nokia")||-1!=a.indexOf("windows ce")||-1!=a.indexOf("sonyericsson")||-1!=a.indexOf("webos")||-1!=a.indexOf("wap")||-1!=a.indexOf("motor")||-1!=a.indexOf("symbian")?!0:!1}
function loadDoc(a,b){var c;window.XMLHttpRequest?c=new XMLHttpRequest:window.ActiveXObject&&(c=new ActiveXObject("Microsoft.XMLHTTP"));c.open("GET",a,!1);c.send(null);404==c.status&&alert("file not found");b(c.responseText)}function disableSelection(a){"undefined"!=typeof a.onselectstart?a.onselectstart=function(){return!1}:"undefined"!=typeof a.style.MozUserSelect?a.style.MozUserSelect="none":a.onmousedown=function(){return!1};a.style.cursor="default"}
function AssertException(a){this.message=a}AssertException.prototype.toString=function(){return"AssertException: "+this.message};function assert(a,b){if(!a)throw new AssertException(b);}function deepCopyUtil(a,b){if(null==a)return a;b=b||{};for(var c in a)"object"===typeof a[c]&&null!=a[c]?(b[c]=a[c].constructor===Array?[]:{},deepCopyUtil(a[c],b[c])):b[c]=a[c];return b}function IdCounter(){}IdCounter.count=0;IdCounter.getUniqueId=function(){IdCounter.count+=1;return"id"+IdCounter.count};
