function TokenScanner(a){this.scanStringsFlag=this.scanNumbersFlag=this.ignoreCommentsFlag=this.ignoreWhitespaceFlag=!1;this.commentStructure="c";this.savedCharacters=[];this.savedTokens=[];this.operators={};this.wordChars="";this.setInput(a||"")}
TokenScanner.prototype.setInput=function(a){this.buffer=a;this.length=a.length;this.lineNumber=this.cp=0;this.savedCharacters=[];this.savedTokens=[];this.lineNumberMap=this.makeLineNumberMap(a);this.lineIndentMap=this.makeLineIndentMap(a);console.log("line number");console.log(this.lineNumberMap);console.log("indent level");console.log(this.lineIndentMap)};
TokenScanner.prototype.setCommentStructure=function(a){"c"!=a&&"python"!=a&&console.error("unsupported comment structure ",a);this.commentStructure=a};TokenScanner.prototype.hasMoreTokens=function(){var a=this.nextToken();this.saveToken(a);return""!=a.text};TokenScanner.prototype.nextTokenIndentLevel=function(){if(!this.hasMoreTokens())throw Error("no more tokens");var a=this.nextToken();this.saveToken(a);return this.lineIndentMap[a.lineNumber]};
TokenScanner.prototype.nextToken=function(){if(0!=this.savedTokens.length)return this.savedTokens.pop();for(;;){this.ignoreWhitespaceFlag&&this.skipSpaces();var a=this.getChar();if(""==a)return this.makeToken("");if("c"==this.commentStructure&&"/"==a&&this.ignoreCommentsFlag){a=this.getChar();if("/"==a){for(;a=this.getChar(),"\n"!=a&&"\r"!=a&&""!=a;);continue}else if("*"==a){for(var b="";;){a=this.getChar();if(""==a||"*"==b&&"/"==a)break;b=a}continue}this.saveChar(a);a="/"}if("python"==this.commentStructure&&
"#"==a&&this.ignoreCommentsFlag)for(console.log("found a python comment");a=this.getChar(),console.log(a),"\n"!=a&&"\r"!=a&&""!=a;);else{if(('"'==a||"'"==a)&&this.scanStringsFlag)return this.saveChar(a),this.makeToken(this.scanString());if(isdigit(a)&&this.scanNumbersFlag)return this.saveChar(a),this.makeToken(this.scanNumber());if(this.isWordCharacter(a))return this.saveChar(a),this.makeToken(this.scanWord());for(b=a;this.isOperatorPrefix(b);){a=this.getChar();if(""==a)break;b+=a}for(;1<b.length&&
!this.isOperator(b);)this.saveChar(b[b.length-1]),b=b.substring(0,b.length-1);return this.makeToken(b)}}};TokenScanner.prototype.makeToken=function(a){return{text:a,lineNumber:this.lineNumberMap[this.cp]}};TokenScanner.prototype.saveToken=function(a){this.savedTokens.push(a)};TokenScanner.prototype.verifyToken=function(a){var b=this.nextToken();if(b.text!=a)throw a='Found "'+b.text+'" when expecting "'+a+'".',a+="\nLine: "+b.lineNumber,Error(a);};
TokenScanner.prototype.verifyNewline=function(){for(;;){var a=this.getChar();if(""==a)break;if(!isspace(a)){if(this.iscomment(a))break;a='Was expecting a new line and found "'+a+'"';a+="\nLine "+this.lineNumberMap[this.cp];throw Error(a);}if("\n"==a)break}};TokenScanner.prototype.iscomment=function(a){if("python"!=this.commentStructure)throw Error("verify newline is not implemented outside python");return"#"==a};
TokenScanner.prototype.setIgnoreWhitespaceFlag=function(a){this.ignoreWhitespaceFlag=a};TokenScanner.prototype.setIgnoreCommentsFlag=function(a){this.ignoreCommentsFlag=a};TokenScanner.prototype.setScanNumbersFlag=function(a){this.scanNumbersFlag=a};TokenScanner.prototype.setScanStringsFlag=function(a){this.scanStringsFlag=a};TokenScanner.prototype.addWordCharacters=function(a){this.wordChars+=a};TokenScanner.prototype.defineOperator=function(a){this.operators[a]=!0};
TokenScanner.prototype.getPosition=function(){switch(this.savedTokens.length){case 0:return this.cp;case 1:return this.cp-this.savedTokens[0].length}throw Error("Internal error: getPosition after two saves");};TokenScanner.prototype.isValidIdentifier=function(a){if(0==a.length)return!1;var b=a.charAt(0);if(!this.isWordCharacter(b)||isdigit(b))return!1;for(b=1;b<a.length;b++)if(!this.isWordCharacter(a.charAt(b)))return!1;return!0};
TokenScanner.prototype.isWordCharacter=function(a){return this.isNonLatinWordCh(a)?!0:isalnum(a)||-1!=this.wordChars.indexOf(a)};TokenScanner.prototype.isNonLatinWordCh=function(a){return/[^\u0000-\u007F]/.test(a)};TokenScanner.prototype.getTokenType=function(a){assert("string"==typeof a);var b=TokenScanner.getTokenType(a);b==TokenScanner.OPERATOR&&(a=a.charAt(0),0<=this.wordChars.indexOf(a)&&(b=TokenScanner.WORD));return b};
TokenScanner.prototype.toString=function(){var a=typeof this;return a=this.buffer.length<TokenScanner.MAX_TO_STRING_LENGTH?a+('("'+this.buffer+'")'):a+("("+this.buffer.length+" chars)")};TokenScanner.MAX_TO_STRING_LENGTH=20;TokenScanner.EOF=-1;TokenScanner.SEPARATOR=0;TokenScanner.WORD=1;TokenScanner.NUMBER=2;TokenScanner.STRING=3;TokenScanner.OPERATOR=4;
TokenScanner.getTokenType=function(a){assert("string"==typeof a);if(""==a)return TokenScanner.EOF;a=a.charAt(0);return isspace(a)?TokenScanner.SEPARATOR:'"'==a||"'"==a?TokenScanner.STRING:isdigit(a)?TokenScanner.NUMBER:isalpha(a)?TokenScanner.WORD:TokenScanner.OPERATOR};TokenScanner.getString=function(a){return eval(a)};TokenScanner.getNumber=function(a){assert("string"==typeof a);return eval(a)};
TokenScanner.prototype.getChar=function(){if(0==this.savedCharacters.length)return this.cp>=this.length?"":this.buffer.charAt(this.cp++);this.cp++;return this.savedCharacters.pop()};TokenScanner.prototype.saveChar=function(a){this.cp--;this.savedCharacters.push(a)};TokenScanner.prototype.skipSpaces=function(){for(;;){var a=this.getChar();if(""==a)break;if(!isspace(a)){this.saveChar(a);break}}};
TokenScanner.prototype.scanWord=function(){for(var a="";;){var b=this.getChar();if(""==b)break;if(!this.isWordCharacter(b)){this.saveChar(b);break}a+=b}return a};TokenScanner.INITIAL_STATE=0;TokenScanner.BEFORE_DECIMAL_POINT=1;TokenScanner.AFTER_DECIMAL_POINT=2;TokenScanner.STARTING_EXPONENT=3;TokenScanner.FOUND_EXPONENT_SIGN=4;TokenScanner.SCANNING_EXPONENT=5;TokenScanner.LEADING_ZERO=6;TokenScanner.SCANNING_HEX=7;TokenScanner.FINAL_STATE=8;
TokenScanner.prototype.scanNumber=function(){for(var a="",b=TokenScanner.INITIAL_STATE;b!=TokenScanner.FINAL_STATE;){var c=this.getChar();switch(b){case TokenScanner.INITIAL_STATE:b="0"==c?TokenScanner.LEADING_ZERO:TokenScanner.BEFORE_DECIMAL_POINT;break;case TokenScanner.BEFORE_DECIMAL_POINT:"."==c?b=TokenScanner.AFTER_DECIMAL_POINT:"E"==c||"e"==c?b=TokenScanner.STARTING_EXPONENT:isdigit(c)||(this.saveChar(c),b=TokenScanner.FINAL_STATE);break;case TokenScanner.AFTER_DECIMAL_POINT:"E"==c||"e"==c?
b=TokenScanner.STARTING_EXPONENT:isdigit(c)||(this.saveChar(c),b=TokenScanner.FINAL_STATE);break;case TokenScanner.STARTING_EXPONENT:"+"==c||"-"==c?b=TokenScanner.FOUND_EXPONENT_SIGN:isdigit(c)?b=TokenScanner.SCANNING_EXPONENT:(this.saveChar(c),b=TokenScanner.FINAL_STATE);break;case TokenScanner.FOUND_EXPONENT_SIGN:isdigit(c)?b=TokenScanner.SCANNING_EXPONENT:(this.saveChar(c),this.saveChar("e"),b=TokenScanner.FINAL_STATE);break;case TokenScanner.SCANNING_EXPONENT:isdigit(c)||(this.saveChar(c),b=TokenScanner.FINAL_STATE);
break;case TokenScanner.LEADING_ZERO:"x"==c||"X"==c?b=TokenScanner.SCANNING_HEX:"."==c?b=TokenScanner.AFTER_DECIMAL_POINT:"E"==c||"e"==c?b=TokenScanner.STARTING_EXPONENT:isdigit(c)||(this.saveChar(c),b=TokenScanner.FINAL_STATE);break;case TokenScanner.SCANNING_HEX:isxdigit(c)||(this.saveChar(c),b=TokenScanner.FINAL_STATE);break;default:b=TokenScanner.FINAL_STATE}b!=TokenScanner.FINAL_STATE&&(a+=c)}return a};
TokenScanner.prototype.scanString=function(){var a="",b=this.getChar();for(a+=b;;){var c=this.getChar();if(""==c)throw Error("Unterminated string");if(c==b)break;a="\\"==c?a+this.scanEscapeCharacter():a+c}return a+b};TokenScanner.prototype.scanEscapeCharacter=function(){var a="\\",b=this.getChar();a+=b;if(isdigit(b)||"x"==b||"u"==b){for(var c=!isdigit(b);;){b=this.getChar();if(c?!isxdigit(b):!isdigit(b))break;a+=b}this.saveChar(b)}return a};
TokenScanner.prototype.isOperator=function(a){return!0===this.operators[a]};TokenScanner.prototype.isOperatorPrefix=function(a){for(var b in this.operators)if(b.startsWith(a))return!0;return!1};TokenScanner.prototype.makeLineNumberMap=function(a){for(var b={},c=0,d=0;d<a.length;d++){var e=a.charAt(d);b[d]=c;"\n"==e&&(c+=1)}return b};TokenScanner.prototype.makeLineIndentMap=function(a){var b={};a=a.split("\n");for(var c=0;c<a.length;c++){let d=this.getIndentLevel(a[c]);b[c]=d}return b};
TokenScanner.prototype.getIndentLevel=function(a){for(var b=0,c=0;c<a.length;c++){var d=a.charAt(c);if(!/\s/.test(d))return b;b++}return a.length};
