function VM(){this.reset();this.globals={};this.operators={};this.functions={}}VM.prototype.run=function(a){this.reset();for(this.call("<stmt>",a);null!=this.cf;)this.step();return this.operandStack.pop()};VM.prototype.reset=function(){this.operandStack=[];this.frameStack=[];this.cf=null};
VM.prototype.compile=function(a,b){if(a instanceof Array){var c=a[0],d=this.operators[c];console.log(c);console.log(d);if(!d)throw Error('Undefined operator "'+c+'"');d.compile(this,a,b)}else switch(TokenScanner.getTokenType(a)){case TokenScanner.WORD:b.push(new LoadIns(a));break;case TokenScanner.NUMBER:b.push(new PushIns(TokenScanner.getNumber(a)));break;case TokenScanner.STRING:b.push(new PushIns(TokenScanner.getString(a)))}};VM.prototype.defineOperator=function(a){this.operators[a.name]=a};
VM.prototype.push=function(a){this.operandStack.push(a)};VM.prototype.pop=function(){if(0==this.operandStack.length)throw Error("Internal error: Operand stack empty");return this.operandStack.pop()};VM.prototype.top=function(){if(0==this.operandStack.length)throw Error("Internal error: Operand stack empty");return this.operandStack[this.operandStack.length-1]};VM.prototype.call=function(a,b){this.frameStack.push(this.cf);this.cf=new VMFrame(a,b);this.cf.scopeChain=new VMScope};
VM.prototype.ret=function(){this.cf=this.frameStack.pop()};VM.prototype.step=function(){null!=this.cf&&(this.cf.pc<this.cf.code.length?this.cf.code[this.cf.pc++].execute(this):this.ret())};VM.prototype.get=function(a){for(var b=this.cf.scopeChain;null!=b;){var c=b.bindings[a];if(void 0!==c)return c;b=b.link}return this.globals[a]};VM.prototype.set=function(a,b){this.globals[a]=b};VM.prototype.toString=function(){return typeof this+"(...)"};function PushIns(a){this.value=a}
PushIns.prototype.toString=function(){return"push "+Parser.unparse(this.value)};PushIns.prototype.execute=function(a){a.push(this.value)};function PopIns(){}PopIns.prototype.toString=function(){return"pop"};PopIns.prototype.execute=function(a){a.pop()};function LoadIns(a){this.variable=a}LoadIns.prototype.toString=function(){return"load "+this.variable};LoadIns.prototype.execute=function(a){a.push(a.get(this.variable))};function StoreIns(a){this.variable=a}
StoreIns.prototype.toString=function(){return"store "+this.variable};StoreIns.prototype.execute=function(a){a.set(this.variable,a.top())};function DupIns(){}DupIns.prototype.toString=function(){return"dup"};DupIns.prototype.execute=function(a){a.push(a.top())};function JumpIns(a,b){this.name=a;this.target=b}JumpIns.prototype.toString=function(){return this.name+" "+this.target};
JumpIns.prototype.execute=function(a){var b=!0;if("jumpt"==this.name||"jumpf"==this.name)b=!!a.pop()==("jumpt"==this.name);b&&(a.cf.pc=this.target)};JumpIns.prototype.setTarget=function(a){this.target=a};function CallIns(a){this.name="call";this.fn=a}CallIns.prototype.toString=function(){return"call "+fn};CallIns.prototype.compile=function(a,b,c){for(var d=b[1],f=b.length-2,e=0;e<f;e++)a.compile(b[2+e],c);c.push(new PushIns(f));c.push(new CallIns(d))};function ReturnIns(){this.name="return"}
ReturnIns.prototype.toString=function(){return this.name};ReturnIns.prototype.compile=function(a,b,c){1<b.length&&a.compile(b[1],c);c.push(this)};ReturnIns.prototype.execute=function(a){a.ret()};function InfixOp(a,b){this.name=a;this.fn=b}InfixOp.prototype.toString=function(){return this.name};InfixOp.prototype.compile=function(a,b,c){a.compile(b[1],c);a.compile(b[2],c);c.push(this)};InfixOp.prototype.execute=function(a){var b=a.pop(),c=a.pop();a.push(this.fn(c,b))};
function PrefixOp(a,b){this.name="pre"+a;this.fn=b}PrefixOp.prototype.toString=function(){return this.name};PrefixOp.prototype.compile=function(a,b,c){a.compile(b[1],c);c.push(this)};PrefixOp.prototype.execute=function(a){a.push(this.fn(a.pop()))};function PostfixOp(a,b){this.name="post"+a;this.fn=b}PostfixOp.prototype.toString=function(){return this.name};PostfixOp.prototype.compile=function(a,b,c){a.compile(b[1],c);c.push(this)};PostfixOp.prototype.execute=function(a){a.push(this.fn(a.pop()))};
function AssignOp(a,b){this.name=a;this.fn=b}AssignOp.prototype.toString=function(){return this.name};AssignOp.prototype.compile=function(a,b,c){this.fn&&a.compile(b[1],c);a.compile(b[2],c);this.fn&&c.push(this);c.push(new StoreIns(b[1]))};AssignOp.prototype.execute=function(a){var b=a.pop(),c=a.pop();a.push(this.fn(c,b))};function VMFrame(a,b){this.name=a;this.code=b;this.pc=0;this.scopeChain=null}function VMScope(){this.bindings={};this.link=null};
