define("ace/mode/python_highlight_rules",["require","exports","module","ace/lib/oop","ace/mode/text_highlight_rules"],function(a,g,h){h=a("../lib/oop");a=a("./text_highlight_rules").TextHighlightRules;var d=function(){this.$rules={start:[{token:"comment",regex:"#.*$"},{token:"string",regex:'(?:r|u|ur|R|U|UR|Ur|uR)?"{3}',next:"qqstring3"},{token:"string",regex:'(?:r|u|ur|R|U|UR|Ur|uR)?"(?=.)',next:"qqstring"},{token:"string",regex:"(?:r|u|ur|R|U|UR|Ur|uR)?'{3}",next:"qstring3"},{token:"string",regex:"(?:r|u|ur|R|U|UR|Ur|uR)?'(?=.)",
next:"qstring"},{token:"constant.numeric",regex:"(?:(?:(?:(?:(?:(?:(?:\\d+)?(?:\\.\\d+))|(?:(?:\\d+)\\.))|(?:\\d+))(?:[eE][+-]?\\d+))|(?:(?:(?:\\d+)?(?:\\.\\d+))|(?:(?:\\d+)\\.)))|\\d+)[jJ]\\b"},{token:"constant.numeric",regex:"(?:(?:(?:(?:(?:(?:\\d+)?(?:\\.\\d+))|(?:(?:\\d+)\\.))|(?:\\d+))(?:[eE][+-]?\\d+))|(?:(?:(?:\\d+)?(?:\\.\\d+))|(?:(?:\\d+)\\.)))"},{token:"constant.numeric",regex:"(?:(?:(?:[1-9]\\d*)|(?:0))|(?:0[oO]?[0-7]+)|(?:0[xX][\\dA-Fa-f]+)|(?:0[bB][01]+))[lL]\\b"},{token:"constant.numeric",
regex:"(?:(?:(?:[1-9]\\d*)|(?:0))|(?:0[oO]?[0-7]+)|(?:0[xX][\\dA-Fa-f]+)|(?:0[bB][01]+))\\b"},{token:this.createKeywordMapper({"invalid.deprecated":"debugger","support.function":"abs|divmod|input|open|staticmethod|all|enumerate|int|ord|str|any|eval|isinstance|pow|sum|basestring|execfile|issubclass|print|super|binfile|iter|property|tuple|bool|filter|len|range|type|bytearray|float|list|raw_input|unichr|callable|format|locals|reduce|unicode|chr|frozenset|long|reload|vars|classmethod|getattr|map|repr|xrange|cmp|globals|max|reversed|zip|compile|hasattr|memoryview|round|__import__|complex|hash|min|set|apply|delattr|help|next|setattr|buffer|dict|hex|object|slice|coerce|dir|id|oct|sorted|intern",
"variable.language":"self|cls","constant.language":"True|False|None|NotImplemented|Ellipsis|__debug__",keyword:"and|as|assert|break|class|continue|def|del|elif|else|except|exec|finally|for|from|global|if|import|in|is|lambda|not|or|pass|print|raise|return|try|while|with|yield|async|await"},"identifier"),regex:"[a-zA-Z_$][a-zA-Z0-9_$]*\\b"},{token:"keyword.operator",regex:"\\+|\\-|\\*|\\*\\*|\\/|\\/\\/|%|<<|>>|&|\\||\\^|~|<|>|<=|=>|==|!=|<>|="},{token:"paren.lparen",regex:"[\\[\\(\\{]"},{token:"paren.rparen",
regex:"[\\]\\)\\}]"},{token:"text",regex:"\\s+"}],qqstring3:[{token:"constant.language.escape",regex:"\\\\(x[0-9A-Fa-f]{2}|[0-7]{3}|[\\\\abfnrtv'\"]|U[0-9A-Fa-f]{8}|u[0-9A-Fa-f]{4})"},{token:"string",regex:'"{3}',next:"start"},{defaultToken:"string"}],qstring3:[{token:"constant.language.escape",regex:"\\\\(x[0-9A-Fa-f]{2}|[0-7]{3}|[\\\\abfnrtv'\"]|U[0-9A-Fa-f]{8}|u[0-9A-Fa-f]{4})"},{token:"string",regex:"'{3}",next:"start"},{defaultToken:"string"}],qqstring:[{token:"constant.language.escape",regex:"\\\\(x[0-9A-Fa-f]{2}|[0-7]{3}|[\\\\abfnrtv'\"]|U[0-9A-Fa-f]{8}|u[0-9A-Fa-f]{4})"},
{token:"string",regex:"\\\\$",next:"qqstring"},{token:"string",regex:'"|$',next:"start"},{defaultToken:"string"}],qstring:[{token:"constant.language.escape",regex:"\\\\(x[0-9A-Fa-f]{2}|[0-7]{3}|[\\\\abfnrtv'\"]|U[0-9A-Fa-f]{8}|u[0-9A-Fa-f]{4})"},{token:"string",regex:"\\\\$",next:"qstring"},{token:"string",regex:"'|$",next:"start"},{defaultToken:"string"}]}};h.inherits(d,a);g.PythonHighlightRules=d});
define("ace/mode/folding/pythonic",["require","exports","module","ace/lib/oop","ace/mode/folding/fold_mode"],function(a,g,h){h=a("../../lib/oop");a=a("./fold_mode").FoldMode;g=g.FoldMode=function(d){this.foldingStartMarker=new RegExp("([\\[{])(?:\\s*)$|("+d+")(?:\\s*)(?:#.*)?$")};h.inherits(g,a);(function(){this.getFoldWidgetRange=function(d,f,l){if(f=d.getLine(l).match(this.foldingStartMarker))return f[1]?this.openingBracketBlock(d,f[1],l,f.index):f[2]?this.indentationBlock(d,l,f.index+f[2].length):
this.indentationBlock(d,l)}}).call(g.prototype)});
define("ace/mode/python","require exports module ace/lib/oop ace/mode/text ace/mode/python_highlight_rules ace/mode/folding/pythonic ace/range".split(" "),function(a,g,h){h=a("../lib/oop");var d=a("./text").Mode,f=a("./python_highlight_rules").PythonHighlightRules,l=a("./folding/pythonic").FoldMode,n=a("../range").Range;a=function(){this.HighlightRules=f;this.foldingRules=new l("\\:");this.$behaviour=this.$defaultBehaviour};h.inherits(a,d);(function(){this.lineCommentStart="#";this.getNextLineIndent=
function(c,b,e){var k=this.$getIndent(b),m=this.getTokenizer().getLineTokens(b,c).tokens;if(m.length&&"comment"==m[m.length-1].type)return k;"start"==c&&b.match(/^.*[\{\(\[:]\s*$/)&&(k+=e);return k};var p={pass:1,"return":1,raise:1,"break":1,"continue":1};this.checkOutdent=function(c,b,e){if("\r\n"!==e&&"\r"!==e&&"\n"!==e)return!1;c=this.getTokenizer().getLineTokens(b.trim(),c).tokens;if(!c)return!1;do b=c.pop();while(b&&("comment"==b.type||"text"==b.type&&b.value.match(/^\s+$/)));return b?"keyword"==
b.type&&p[b.value]:!1};this.autoOutdent=function(c,b,e){e+=1;c=this.$getIndent(b.getLine(e));var k=b.getTabString();c.slice(-k.length)==k&&b.remove(new n(e,c.length-k.length,e,c.length))};this.$id="ace/mode/python"}).call(a.prototype);g.Mode=a});(function(){window.require(["ace/mode/python"],function(a){"object"==typeof module&&"object"==typeof exports&&module&&(module.exports=a)})})();
