var CodeMirrorConfig=window.CodeMirrorConfig||{},CodeMirror=function(){function C(a,b){for(var c in b)a.hasOwnProperty(c)||(a[c]=b[c])}function D(a,b){for(var c=0;c<a.length;c++)b(a[c])}function E(a){var b=document.createElement("DIV"),c=document.createElement("DIV");b.style.position="absolute";b.style.height="100%";if(b.style.setExpression)try{b.style.setExpression("height","this.previousSibling.offsetHeight + 'px'")}catch(e){}b.style.top="0px";b.style.overflow="hidden";a.appendChild(b);c.className=
"CodeMirror-line-numbers";b.appendChild(c);return b}function F(a){"string"==typeof a.parserfile&&(a.parserfile=[a.parserfile]);"string"==typeof a.stylesheet&&(a.stylesheet=[a.stylesheet]);var b=['<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head>'];b.push('<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>');D(a.stylesheet,function(c){b.push('<link rel="stylesheet" type="text/css" href="'+c+'"/>')});D(a.basefiles.concat(a.parserfile),
function(c){b.push('<script type="text/javascript" src="'+a.path+c+'">\x3c/script>')});b.push('</head><body style="border-width: 0;" class="editbox" spellcheck="'+(a.disableSpellcheck?"false":"true")+'"></body></html>');return b.join("")}function r(a,b){b.dumbTabs?b.tabMode="spaces":b.normalTab&&(b.tabMode="default");this.options=b=b||{};C(b,CodeMirrorConfig);var c=this.frame=document.createElement("IFRAME");b.iframeClass&&(c.className=b.iframeClass);c.frameBorder=0;c.style.border="0";c.style.width=
"100%";c.style.height="100%";c.style.display="block";var e=this.wrapping=document.createElement("DIV");e.style.position="relative";e.className="CodeMirror-wrapping";e.style.width=b.width;e.style.height=b.height;var f=this.textareaHack=document.createElement("TEXTAREA");e.appendChild(f);f.style.position="absolute";f.style.left="-10000px";f.style.width="10px";c.CodeMirror=this;b.domain&&G?(this.html=F(b),c.src="javascript:(function(){document.open();"+(b.domain?'document.domain="'+b.domain+'";':"")+
"document.write(window.frameElement.CodeMirror.html);document.close();})()"):c.src="javascript:false";a.appendChild?a.appendChild(e):a(e);e.appendChild(c);b.lineNumbers&&(this.lineNumbers=E(e));this.win=c.contentWindow;b.domain&&G||(this.win.document.open(),this.win.document.write(F(b)),this.win.document.close())}C(CodeMirrorConfig,{stylesheet:"",path:"",parserfile:[],basefiles:"util.js stringstream.js select.js undo.js editor.js tokenize.js".split(" "),iframeClass:null,passDelay:200,passTime:50,
lineNumberDelay:200,lineNumberTime:50,continuousScanning:!1,saveFunction:null,onChange:null,undoDepth:50,undoDelay:800,disableSpellcheck:!0,textWrapping:!0,readOnly:!1,width:"",height:"300px",autoMatchParens:!1,parserConfig:null,tabMode:"indent",reindentOnLoad:!1,activeTokens:null,cursorActivity:null,lineNumbers:!1,indentUnit:2,domain:null});var G=document.selection&&window.ActiveXObject&&/MSIE/.test(navigator.userAgent);r.prototype={init:function(){this.options.initCallback&&this.options.initCallback(this);
this.options.lineNumbers&&this.activateLineNumbers();this.options.reindentOnLoad&&this.reindent()},getCode:function(){return this.editor.getCode()},setCode:function(a){this.editor.importCode(a)},selection:function(){this.focusIfIE();return this.editor.selectedText()},reindent:function(){this.editor.reindent()},reindentSelection:function(){this.focusIfIE();this.editor.reindentSelection(null)},focusIfIE:function(){this.win.select.ie_selection&&this.focus()},focus:function(){this.win.focus();this.editor.selectionSnapshot&&
this.win.select.setBookmark(this.win.document.body,this.editor.selectionSnapshot)},replaceSelection:function(a){this.focus();this.editor.replaceSelection(a);return!0},replaceChars:function(a,b,c){this.editor.replaceChars(a,b,c)},getSearchCursor:function(a,b,c){return this.editor.getSearchCursor(a,b,c)},undo:function(){this.editor.history.undo()},redo:function(){this.editor.history.redo()},historySize:function(){return this.editor.history.historySize()},clearHistory:function(){this.editor.history.clear()},
grabKeys:function(a,b){this.editor.grabKeys(a,b)},ungrabKeys:function(){this.editor.ungrabKeys()},setParser:function(a){this.editor.setParser(a)},setSpellcheck:function(a){this.win.document.body.spellcheck=a},setStylesheet:function(a){"string"===typeof a&&(a=[a]);for(var b={},c={},e=this.win.document.getElementsByTagName("link"),f=0,d;d=e[f];f++)if(-1!==d.rel.indexOf("stylesheet"))for(var m=0;m<a.length;m++){var g=a[m];d.href.substring(d.href.length-g.length)===g&&(b[d.href]=!0,c[g]=!0)}for(f=0;d=
e[f];f++)-1!==d.rel.indexOf("stylesheet")&&(d.disabled=!(d.href in b));for(m=0;m<a.length;m++)g=a[m],g in c||(d=this.win.document.createElement("link"),d.rel="stylesheet",d.type="text/css",d.href=g,this.win.document.getElementsByTagName("head")[0].appendChild(d))},setTextWrapping:function(a){a!=this.options.textWrapping&&(this.win.document.body.style.whiteSpace=a?"":"nowrap",this.options.textWrapping=a,this.lineNumbers&&(this.setLineNumbers(!1),this.setLineNumbers(!0)))},setIndentUnit:function(a){this.win.indentUnit=
a},setUndoDepth:function(a){this.editor.history.maxDepth=a},setTabMode:function(a){this.options.tabMode=a},setLineNumbers:function(a){a&&!this.lineNumbers?(this.lineNumbers=E(this.wrapping),this.activateLineNumbers()):!a&&this.lineNumbers&&(this.wrapping.removeChild(this.lineNumbers),this.wrapping.style.marginLeft="",this.lineNumbers=null)},cursorPosition:function(a){this.focusIfIE();return this.editor.cursorPosition(a)},firstLine:function(){return this.editor.firstLine()},lastLine:function(){return this.editor.lastLine()},
nextLine:function(a){return this.editor.nextLine(a)},prevLine:function(a){return this.editor.prevLine(a)},lineContent:function(a){return this.editor.lineContent(a)},setLineContent:function(a,b){this.editor.setLineContent(a,b)},removeLine:function(a){this.editor.removeLine(a)},insertIntoLine:function(a,b,c){this.editor.insertIntoLine(a,b,c)},selectLines:function(a,b,c,e){this.win.focus();this.editor.selectLines(a,b,c,e)},nthLine:function(a){for(var b=this.firstLine();1<a&&!1!==b;a--)b=this.nextLine(b);
return b},lineNumber:function(a){for(var b=0;!1!==a;)b++,a=this.prevLine(a);return b},jumpToLine:function(a){"number"==typeof a&&(a=this.nthLine(a));this.selectLines(a,0);this.win.focus()},currentLine:function(){return this.lineNumber(this.cursorLine())},cursorLine:function(){return this.cursorPosition().line},activateLineNumbers:function(){function a(){if(0!=f.offsetWidth){for(var h=f;h.parentNode;h=h.parentNode);if(t.parentNode&&h==document&&d.Editor)t.offsetWidth!=A&&(A=t.offsetWidth,t.style.left=
"-"+(f.parentNode.style.marginLeft=A+"px"));else{try{z()}catch(w){}clearInterval(H)}}}function b(){t.scrollTop=g.scrollTop||m.documentElement.scrollTop||0}function c(){function h(){for(var n=50+Math.max(g.offsetHeight,Math.max(f.offsetHeight,g.scrollHeight||0)),x=(new Date).getTime()+p.options.lineNumberTime;k.offsetHeight<n&&(!k.firstChild||k.offsetHeight);)if(k.appendChild(document.createElement("DIV")),k.lastChild.innerHTML=w++,(new Date).getTime()>x){q&&clearTimeout(q);q=setTimeout(h,p.options.lineNumberDelay);
break}b()}var w=1,q,u=d.addEventHandler(d,"scroll",h,!0),l=d.addEventHandler(d,"resize",h,!0);z=function(){u();l();q&&clearTimeout(q)};h()}function e(){function h(y){n||=k.appendChild(document.createElement("DIV"));n.innerHTML=y;B=n.offsetHeight+n.offsetTop;n=n.nextSibling}function w(){if(k.parentNode&&k.parentNode==p.lineNumbers){for(var y=(new Date).getTime()+p.options.lineNumberTime;l;){for(h(x++);l&&!d.isBR(l);l=l.nextSibling)for(var I=l.offsetTop+l.offsetHeight;k.offsetHeight&&I-3>B;)h("&nbsp;");
l&&(l=l.nextSibling);if((new Date).getTime()>y){v=setTimeout(w,p.options.lineNumberDelay);return}}for(y=50+Math.max(g.offsetHeight,Math.max(f.offsetHeight,g.scrollHeight||0));n||k.offsetHeight<y&&(!k.firstChild||k.offsetHeight);)h(x++);b()}}function q(){b();l=g.firstChild;n=k.firstChild;B=0;x=1;w()}function u(){v&&clearTimeout(v);p.editor.allClean()?q():v=setTimeout(u,200)}var l,n,x,B;q();var v=null;p.updateNumbers=u;var J=d.addEventHandler(d,"scroll",b,!0),K=d.addEventHandler(d,"resize",u,!0);z=
function(){v&&clearTimeout(v);p.updateNumbers==u&&(p.updateNumbers=null);J();K()}}var f=this.frame,d=f.contentWindow,m=d.document,g=m.body,t=this.lineNumbers,k=t.firstChild,p=this,A=null,z=function(){};a();var H=setInterval(a,500);(this.options.textWrapping?e:c)()}};r.InvalidLineHandle={toString:function(){return"CodeMirror.InvalidLineHandle"}};r.replace=function(a){"string"==typeof a&&(a=document.getElementById(a));return function(b){a.parentNode.replaceChild(b,a)}};r.fromTextArea=function(a,b){"string"==
typeof a&&(a=document.getElementById(a));b=b||{};a.style.width&&null==b.width&&(b.width=a.style.width);a.style.height&&null==b.height&&(b.height=a.style.height);null==b.content&&(b.content=a.value);if(a.form){function e(){a.value=c.getCode()}"function"==typeof a.form.addEventListener?a.form.addEventListener("submit",e,!1):a.form.attachEvent("onsubmit",e)}a.style.display="none";var c=new r(function(e){a.nextSibling?a.parentNode.insertBefore(e,a.nextSibling):a.parentNode.appendChild(e)},b);return c};
r.isProbablySupported=function(){var a;return window.opera?9.52<=Number(window.opera.version()):/Apple Computers, Inc/.test(navigator.vendor)&&(a=navigator.userAgent.match(/Version\/(\d+(?:\.\d+)?)\./))?3<=Number(a[1]):document.selection&&window.ActiveXObject&&(a=navigator.userAgent.match(/MSIE (\d+(?:\.\d*)?)\b/))?6<=Number(a[1]):(a=navigator.userAgent.match(/gecko\/(\d{8})/i))?20050901<=Number(a[1]):(a=navigator.userAgent.match(/AppleWebKit\/(\d+)/))?525<=Number(a[1]):null};return r}();
