jQuery.fn.boxy=function(a){a=a||{};return this.each(function(){var b=this.nodeName.toLowerCase(),c=this;"a"==b?jQuery(this).click(function(){var d=Boxy.linkedTo(this),e=this.getAttribute("href"),f=jQuery.extend({actuator:this,title:this.title},a);d?d.show():0<=e.indexOf("#")?(d=jQuery(e.substr(e.indexOf("#"))),e=d.clone(!0),d.remove(),f.unloadOnHide=!1,new Boxy(e,f)):(f.cache||(f.unloadOnHide=!0),Boxy.load(this.href,f));return!1}):"form"==b&&jQuery(this).bind("submit.boxy",function(){Boxy.confirm(a.message||
"Please confirm:",function(){jQuery(c).unbind("submit.boxy").submit()});return!1})})};
function Boxy(a,b){this.boxy=jQuery(Boxy.WRAPPER);jQuery.data(this.boxy[0],"boxy",this);this.visible=!1;this.options=jQuery.extend({},Boxy.DEFAULTS,b||{});this.options.modal&&(this.options=jQuery.extend(this.options,{center:!0,draggable:!1}));this.options.actuator&&jQuery.data(this.options.actuator,"active.boxy",this);this.setContent(a||"<div></div>");this._setupTitleBar();this.boxy.css("display","none").appendTo(document.body);this.toTop();this.options.fixed&&(jQuery.browser.msie&&7>jQuery.browser.version?
this.options.fixed=!1:this.boxy.addClass("fixed"));this.options.center&&Boxy._u(this.options.x,this.options.y)?this.center():this.moveTo(Boxy._u(this.options.x)?this.options.x:Boxy.DEFAULT_X,Boxy._u(this.options.y)?this.options.y:Boxy.DEFAULT_Y);this.options.show&&this.show()}Boxy.EF=function(){};
jQuery.extend(Boxy,{WRAPPER:"<table cellspacing='0' cellpadding='0' border='0' class='boxy-wrapper'><tr><td class='top-left'></td><td class='top'></td><td class='top-right'></td></tr><tr><td class='left'></td><td class='boxy-inner'></td><td class='right'></td></tr><tr><td class='bottom-left'></td><td class='bottom'></td><td class='bottom-right'></td></tr></table>",DEFAULTS:{title:null,closeable:!0,draggable:!0,clone:!1,actuator:null,center:!0,show:!0,modal:!1,fixed:!0,closeText:"[close]",unloadOnHide:!1,
clickToFront:!1,behaviours:Boxy.EF,afterDrop:Boxy.EF,afterShow:Boxy.EF,afterHide:Boxy.EF,beforeUnload:Boxy.EF},DEFAULT_X:50,DEFAULT_Y:50,zIndex:1337,dragConfigured:!1,resizeConfigured:!1,dragging:null,load:function(a,b){b=b||{};var c={url:a,type:"GET",dataType:"html",cache:!1,success:function(d){d=jQuery(d);b.filter&&(d=jQuery(b.filter,d));new Boxy(d,b)}};jQuery.each(["type","cache"],function(){this in b&&(c[this]=b[this],delete b[this])});jQuery.ajax(c)},get:function(a){a=jQuery(a).parents(".boxy-wrapper");
return a.length?jQuery.data(a[0],"boxy"):null},linkedTo:function(a){return jQuery.data(a,"active.boxy")},alert:function(a,b,c){return Boxy.ask(a,["OK"],b,c)},confirm:function(a,b,c){return Boxy.ask(a,["OK","Cancel"],function(d){"OK"==d&&b()},c)},ask:function(a,b,c,d){d=jQuery.extend({modal:!0,closeable:!1},d||{},{show:!0,unloadOnHide:!0});a=jQuery("<div></div>").append(jQuery('<div class="question"></div>').html(a));var e={},f=[];if(b instanceof Array)for(var g=0;g<b.length;g++)e[b[g]]=b[g],f.push(b[g]);
else for(g in b)e[b[g]]=g,f.push(b[g]);b=jQuery('<form class="answers"></form>');b.html(jQuery.map(f,function(h){return"<input type='button' value='"+h+"' />"}).join(" "));jQuery("input[type=button]",b).click(function(){var h=this;Boxy.get(this).hide(function(){c&&c(e[h.value])})});a.append(b);new Boxy(a,d)},isModalVisible:function(){return 0<jQuery(".boxy-modal-blackout").length},_u:function(){for(var a=0;a<arguments.length;a++)if("undefined"!=typeof arguments[a])return!1;return!0},_handleResize:function(a){a=
jQuery(document);jQuery(".boxy-modal-blackout").css("display","none").css({width:a.width(),height:a.height()}).css("display","block")},_handleDrag:function(a){var b;(b=Boxy.dragging)&&b[0].boxy.css({left:a.pageX-b[1],top:a.pageY-b[2]})},_nextZ:function(){return Boxy.zIndex++},_viewport:function(){var a=document.documentElement,b=document.body,c=window;return jQuery.extend(jQuery.browser.msie?{left:b.scrollLeft||a.scrollLeft,top:b.scrollTop||a.scrollTop}:{left:c.pageXOffset,top:c.pageYOffset},Boxy._u(c.innerWidth)?
Boxy._u(a)||Boxy._u(a.clientWidth)||0==a.clientWidth?{width:b.clientWidth,height:b.clientHeight}:{width:a.clientWidth,height:a.clientHeight}:{width:c.innerWidth,height:c.innerHeight})}});
Boxy.prototype={estimateSize:function(){this.boxy.css({visibility:"hidden",display:"block"});var a=this.getSize();this.boxy.css("display","none").css("visibility","visible");return a},getSize:function(){return[this.boxy.width(),this.boxy.height()]},getContentSize:function(){var a=this.getContent();return[a.width(),a.height()]},getPosition:function(){var a=this.boxy[0];return[a.offsetLeft,a.offsetTop]},getCenter:function(){var a=this.getPosition(),b=this.getSize();return[Math.floor(a[0]+b[0]/2),Math.floor(a[1]+
b[1]/2)]},getInner:function(){return jQuery(".boxy-inner",this.boxy)},getContent:function(){return jQuery(".boxy-content",this.boxy)},setContent:function(a){a=jQuery(a).css({display:"block"}).addClass("boxy-content");this.options.clone&&(a=a.clone(!0));this.getContent().remove();this.getInner().append(a);this._setupDefaultBehaviours(a);this.options.behaviours.call(this,a);return this},moveTo:function(a,b){this.moveToX(a).moveToY(b);return this},moveToX:function(a){"number"==typeof a?this.boxy.css({left:a}):
this.centerX();return this},moveToY:function(a){"number"==typeof a?this.boxy.css({top:a}):this.centerY();return this},centerAt:function(a,b){var c=this[this.visible?"getSize":"estimateSize"]();"number"==typeof a&&this.moveToX(a-c[0]/2);"number"==typeof b&&this.moveToY(b-c[1]/2);return this},centerAtX:function(a){return this.centerAt(a,null)},centerAtY:function(a){return this.centerAt(null,a)},center:function(a){var b=Boxy._viewport(),c=this.options.fixed?[0,0]:[b.left,b.top];a&&"x"!=a||this.centerAt(c[0]+
b.width/2,null);a&&"y"!=a||this.centerAt(null,c[1]+b.height/2);return this},centerX:function(){return this.center("x")},centerY:function(){return this.center("y")},resize:function(a,b,c){if(this.visible)return a=this._getBoundsForResize(a,b),this.boxy.css({left:a[0],top:a[1]}),this.getContent().css({width:a[2],height:a[3]}),c&&c(this),this},tween:function(a,b,c){if(this.visible){a=this._getBoundsForResize(a,b);var d=this;this.boxy.stop().animate({left:a[0],top:a[1]});this.getContent().stop().animate({width:a[2],
height:a[3]},function(){c&&c(d)});return this}},isVisible:function(){return this.visible},show:function(){if(!this.visible){if(this.options.modal){var a=this;Boxy.resizeConfigured||(Boxy.resizeConfigured=!0,jQuery(window).resize(function(){Boxy._handleResize()}));this.modalBlackout=jQuery('<div class="boxy-modal-blackout"></div>').css({zIndex:Boxy._nextZ(),opacity:.7,width:jQuery(document).width(),height:jQuery(document).height()}).appendTo(document.body);this.toTop();this.options.closeable&&jQuery(document.body).bind("keypress.boxy",
function(b){27==(b.which||b.keyCode)&&(a.hide(),jQuery(document.body).unbind("keypress.boxy"))})}this.boxy.stop().css({opacity:1}).show();this.visible=!0;this._fire("afterShow");return this}},hide:function(a){if(this.visible){var b=this;this.options.modal&&(jQuery(document.body).unbind("keypress.boxy"),this.modalBlackout.animate({opacity:0},function(){jQuery(this).remove()}));this.boxy.stop().animate({opacity:0},300,function(){b.boxy.css({display:"none"});b.visible=!1;b._fire("afterHide");a&&a(b);
b.options.unloadOnHide&&b.unload()});return this}},toggle:function(){this[this.visible?"hide":"show"]();return this},hideAndUnload:function(a){this.options.unloadOnHide=!0;this.hide(a);return this},unload:function(){this._fire("beforeUnload");this.boxy.remove();this.options.actuator&&jQuery.data(this.options.actuator,"active.boxy",!1)},toTop:function(){this.boxy.css({zIndex:Boxy._nextZ()});return this},getTitle:function(){return jQuery("> .title-bar h2",this.getInner()).html()},setTitle:function(a){jQuery("> .title-bar h2",
this.getInner()).html(a);return this},_getBoundsForResize:function(a,b){var c=this.getContentSize();c=[a-c[0],b-c[1]];var d=this.getPosition();return[Math.max(d[0]-c[0]/2,0),Math.max(d[1]-c[1]/2,0),a,b]},_setupTitleBar:function(){if(this.options.title){var a=this,b=jQuery("<div class='title-bar'></div>").html("<h2>"+this.options.title+"</h2>");this.options.closeable&&b.append(jQuery("<a href='#' class='close'></a>").html(this.options.closeText));this.options.draggable&&(b[0].onselectstart=function(){return!1},
b[0].unselectable="on",b[0].style.MozUserSelect="none",Boxy.dragConfigured||(jQuery(document).mousemove(Boxy._handleDrag),Boxy.dragConfigured=!0),b.mousedown(function(c){a.toTop();Boxy.dragging=[a,c.pageX-a.boxy[0].offsetLeft,c.pageY-a.boxy[0].offsetTop];jQuery(this).addClass("dragging")}).mouseup(function(){jQuery(this).removeClass("dragging");Boxy.dragging=null;a._fire("afterDrop")}));this.getInner().prepend(b);this._setupDefaultBehaviours(b)}},_setupDefaultBehaviours:function(a){var b=this;this.options.clickToFront&&
a.click(function(){b.toTop()});jQuery(".close",a).click(function(){b.hide();return!1}).mousedown(function(c){c.stopPropagation()})},_fire:function(a){this.options[a].call(this)}};
